<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - BocaNoticias</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            background: #f9fafb;
            margin: 0;
            padding: 20px;
          }
          .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
          }
          h1 {
            color: #2563eb;
            border-bottom: 3px solid #2563eb;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          .intro {
            background: #eff6ff;
            border-left: 4px solid #2563eb;
            padding: 15px;
            margin-bottom: 30px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 0.8rem;
          }
          th {
            background: #2563eb;
            color: white;
            text-align: left;
            padding: 8px 10px;
            font-weight: 600;
            font-size: 0.75rem;
            white-space: nowrap;
          }
          td {
            padding: 3px 10px;
            border-bottom: 1px solid #d1d5db;
            font-size: 0.75rem;
          }
          tbody tr:nth-child(odd) {
            background: #f3f4f6;
          }
          tbody tr:nth-child(even) {
            background: #ffffff;
          }
          tr:hover {
            background: #e5e7eb !important;
          }
          a {
            color: #2c2c2cff;
            text-decoration: none;
            font-size: 0.75rem;
          }
          a:hover {
            text-decoration: underline;
          }
          .url {
            word-break: normal;
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 500px;
          }
          .meta {
            color: #6b7280;
            font-size: 0.7rem;
            white-space: nowrap;
          }
          .priority {
            font-weight: 600;
            color: #059669;
            white-space: nowrap;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 0.875rem;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>🗺️ XML Sitemap</h1>
          
          <div class="intro">
            <p>Generated by <strong style="color: #dc2626;">Yoast SEO</strong>, this is an XML Sitemap, meant for consumption by search engines.</p>
            <p>You can find more information about XML sitemaps on <a href="https://sitemaps.org/" target="_blank">sitemaps.org</a>.</p>
            
            <xsl:if test="s:urlset/s:url">
              <p>📊 This XML Sitemap contains <strong><xsl:value-of select="count(s:urlset/s:url)"/> URLs</strong>.</p>
            </xsl:if>
            
            <xsl:if test="s:sitemapindex/s:sitemap">
              <p>📑 This XML Sitemap Index file contains <strong><xsl:value-of select="count(s:sitemapindex/s:sitemap)"/> sitemaps</strong>.</p>
            </xsl:if>
          </div>

          <xsl:if test="s:urlset/s:url">
            <table>
              <thead>
                <tr>
                  <th>URL</th>
                  <th style="width: 1%">Images</th>
                  <th style="width: 1%">Last Mod.</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="s:urlset/s:url">
                  <tr>
                    <td class="url">
                      <a href="{s:loc}" target="_blank">
                        <xsl:value-of select="s:loc"/>
                      </a>
                    </td>
                    <td class="meta" style="text-align: center;">
                      <xsl:choose>
                        <xsl:when test="image:image/image:loc">
                          <a href="{image:image/image:loc}" target="_blank" style="color: #059669;">
                            📷 <xsl:value-of select="count(image:image)"/>
                          </a>
                        </xsl:when>
                        <xsl:otherwise>-</xsl:otherwise>
                      </xsl:choose>
                    </td>
                    <td class="meta" style="text-align: center;">
                      <xsl:value-of select="s:lastmod"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <xsl:if test="s:sitemapindex/s:sitemap">
            <h2>📑 Sitemap Index</h2>
            <table>
              <thead>
                <tr>
                  <th>Sitemap</th>
                  <th>Last Mod.</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="s:sitemapindex/s:sitemap">
                  <tr>
                    <td class="url">
                      <a href="{s:loc}" target="_blank">
                        <xsl:value-of select="s:loc"/>
                      </a>
                    </td>
                    <td class="meta">
                      <xsl:value-of select="substring(s:lastmod, 0, 11)"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <div class="footer">
            <p>🚀 Generated by <strong style="color: #dc2626;">Yoast SEO</strong> for <strong>BocaNoticias</strong></p>
            <p>Optimized for search engines | Maximum 1,000 URLs per sitemap | Powered by Next.js</p>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
